<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Balls.Protocol\Balls.Protocol.csproj" />
    <ProjectReference Include="..\..\src\Balls.Transport.Lan\Balls.Transport.Lan.csproj" />
  </ItemGroup>
</Project>
