<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Balls.Cli\Balls.Cli.csproj" />
    <ProjectReference Include="..\..\src\Balls.Core\Balls.Core.csproj" />
    <ProjectReference Include="..\..\src\Balls.Daemon\Balls.Daemon.csproj" />
    <ProjectReference Include="..\..\src\Balls.Host\Balls.Host.csproj" />
    <ProjectReference Include="..\..\src\Balls.Platform\Balls.Platform.csproj" />
    <ProjectReference Include="..\..\src\Balls.Platform.Linux\Balls.Platform.Linux.csproj" />
    <ProjectReference Include="..\..\src\Balls.Platform.Windows\Balls.Platform.Windows.csproj" />
    <ProjectReference Include="..\..\src\Balls.Protocol\Balls.Protocol.csproj" />
    <ProjectReference Include="..\..\src\Balls.Storage.Sqlite\Balls.Storage.Sqlite.csproj" />
    <ProjectReference Include="..\..\src\Balls.Transport.Lan\Balls.Transport.Lan.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="MSTest.TestAdapter" />
    <PackageReference Include="MSTest.TestFramework" />
  </ItemGroup>
</Project>
