<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>balls</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Balls.Host\Balls.Host.csproj" />
    <ProjectReference Include="..\Balls.Platform\Balls.Platform.csproj" />
    <ProjectReference Include="..\Balls.Protocol\Balls.Protocol.csproj" />
  </ItemGroup>
</Project>
