<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>balls-bootstrap-windows-x64</AssemblyName>
    <RootNamespace>Balls.Bootstrap.Windows</RootNamespace>
    <PublishSingleFile Condition="'$(RuntimeIdentifier)' != ''">true</PublishSingleFile>
    <SelfContained Condition="'$(RuntimeIdentifier)' != ''">true</SelfContained>
    <EnableCompressionInSingleFile Condition="'$(RuntimeIdentifier)' != ''">true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract Condition="'$(RuntimeIdentifier)' != ''">true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
</Project>
